### ISSUE TITLE
Log error message 'This plugin slows down Homebridge. The read handler for the characteristic 'LastActivation' didn't respond at all!'

### ISSUE THREAD

**Issue by townsmcp** [mfkrause/homebridge-people-pro#6]
Hi,
I am running HomeBridge 1.3.0 and I have upgraded and tried 1.3.1 and 1.3.1beta8 and Im getting the following message in the logs every 10 seconds:

[23/02/2021, 09:53:40] [homebridge-people-pro] This plugin slows down Homebridge. The read handler for the characteristic 'LastActivation' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.

Can this be looked into please?

**Comment by mfkrause** [comment]
Hi there,
thanks for the report. I don't see this behavior in my Homebridge (v1.3.1 as well) - could you please share your plugin config and some information about your Homebridge setup like your OS and Node version? If you're using homebridge-config-ui-x, you can simply copy and paste the "System Information" field from the homepage.

I will look into this then. Thanks!

**Comment by townsmcp** [comment]
@mfkrause thanks. The system info shows:
![image](https://user-images.githubusercontent.com/14061617/108833945-69dc8980-75c5-11eb-93fa-6609b504322d.png)

Plugin config:
![image](https://user-images.githubusercontent.com/14061617/108834062-97293780-75c5-11eb-8ccd-63daa9a61d28.png)

**Comment by townsmcp** [comment]
@mfkrause think I just saw my problem - 'Cheryl People Pro' has the MAC instead of IP 🤭

**Comment by townsmcp** [comment]
DOH,
Just added Cheryl back with IP address rather than MAC, restarted HomeBridge and Im getting the following message again:
![image](https://user-images.githubusercontent.com/14061617/108834837-8d540400-75c6-11eb-9b11-8b20d3e6f176.png)

**Comment by mfkrause** [comment]
Thanks for the info. Going to look into this this week.
The MAC address would have been my first bet as well - MAC address look-ups are not yet supported, only IP address for now.

What you can try in the meantime to see if any of this stops the warning from being printed:

- Disable "nooneSensor" as well.
- Change all sensors (including anyone and noone) to "occupancy" instead of "motion".

If any of these two options stop this behavior, please let me know - this would help narrowing down the source of this bug even more.

edit: Just took a quick look into the appropriate code location and I think I know where this warning comes from. Still, it would be great if you could perform the two tests above anyways!

**Comment by townsmcp** [comment]
@mfkrause sure. Happy to help where I can.
So the NooneSensor is already disabled and Im seeing the printed message in the logs.

Changed both entities to Occupancy sensor instead of motion.
Rebooted HomeBridge and so far (running for 20 minutes) and no error in the logs. Seems like it is when set to Motion sensor rather than Occupancy

**Comment by mfkrause** [comment]
Hey, thanks for the additional input.
Already fixed - the patch was easier than expected after I was able to replicate this problem on my end.

Please update to v0.9.3. You can then revert your sensors to motion sensors if you'd like, the warning shouldn't appear again.
